const fs = require('fs')
// fs.mkdirSync('Sam')
// fs.writeFileSync('./Sam/data.text',"My Name is sam")
// fs.appendFileSync("./Sam/data.text","I am an Enigneer..")
//  const myData = fs.readFileSync("./Sam/data.text",'utf-8')
// console.log(myData)
// fs.renameSync('./Sam/MyData.text','./Sam/data.text')
// fs.unlinkSync('./Sam/data.text')
//fs.rmdirSync('Sam')
